### ISSUE TITLE
예치금 충전용 가상계좌 설정 기능 오류

### ISSUE THREAD

**Issue by an14700** [roeniss/dhlottery-api#109]
예치금 충전 가상계좌 기능에 오류가 있어 이슈 보고드립니당. 

lottery_client.py 247라인의 resp.text를 로그로 출력하면 다음과 같습니다. 
무언가 인터페이스가 변경된 것 같은데 정확한 원인은 제가 찾기 어려울 것 같습니다. 
`<script>alert('일시적인 오류가 발생했습니다.');</script>    `

아래는 trace 로그입니다. (라인은 안맞을 수 있습니당.)

> Traceback (most recent call last):
>   File "/Users/path/WorkSpace/PythonProjects/lottery/dhapi/port/lottery_client.py", line 257, in assign_virtual_account
>     전용가상계좌 = elem[0].select("span")[0].contents[0]
>                    ~~~~^^^
> IndexError: list index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/path/WorkSpace/PythonProjects/lottery/lottery.py", line 75, in <module>
>     client.assign_virtual_account(Deposit(50000))
>   File "/Users/path/WorkSpace/PythonProjects/lottery/dhapi/port/lottery_client.py", line 262, in assign_virtual_account
>     raise RuntimeError("❗ 가상계좌를 할당하지 못했습니다.")
> RuntimeError: ❗ 가상계좌를 할당하지 못했습니다.

아래는 `dhapi assign-virtual-account 50000 -d`로 실행한  로그입니다.

>  DEBUG    Starting new HTTPS connection (1): dhlottery.co.kr:443                                                       connectionpool.py:1019
>            DEBUG    https://dhlottery.co.kr:443 "POST /nicePay.do?method=nicePayProcess HTTP/1.1" 200 None                        connectionpool.py:474
>            DEBUG    resp: <Response [200]>                                                                                        lottery_client.py:247
>            DEBUG    elem: []                                                                                                      lottery_client.py:253
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ /home/lottery/.venv/lib/python3.9/site-packages/dhapi/port/lottery_client.py:255 in    │
> │ assign_virtual_account                                                                           │
> │                                                                                                  │
> │   252 │   │   │                                                                                  │
> │   253 │   │   │   logger.debug(f"elem: {elem}")                                                  │
> │   254 │   │   │                                                                                  │
> │ ❱ 255 │   │   │   전용가상계좌 = elem[0].select("span")[0].contents[0]                           │
> │   256 │   │   │   결제신청금액 = elem[0].select(".color_key1")[0].contents[0]                    │
> │   257 │   │   │                                                                                  │
> │   258 │   │   │   self._lottery_endpoint.print_result_of_assign_virtual_account(전용가상계좌,    │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> IndexError: list index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ /home/mypi/Work/lottery/.venv/lib/python3.9/site-packages/dhapi/router/router.py:51 in           │
> │ assign_virtual_account                                                                           │
> │                                                                                                  │
> │    48 │   deposit = Deposit(amount)                                                              │
> │    49 │                                                                                          │
> │    50 │   client = build_lottery_client(user, None)                                              │
> │ ❱  51 │   client.assign_virtual_account(deposit)                                                 │
> │    52                                                                                            │
> │    53                                                                                            │
> │    54 @app.command(                                                                              │
> │                                                                                                  │
> │ /home/lottery/.venv/lib/python3.9/site-packages/dhapi/port/lottery_client.py:260 in    │
> │ assign_virtual_account                                                                           │
> │                                                                                                  │
> │   257 │   │   │                                                                                  │
> │   258 │   │   │   self._lottery_endpoint.print_result_of_assign_virtual_account(전용가상계좌,    │
> │   259 │   │   except Exception:                                                                  │
> │ ❱ 260 │   │   │   raise RuntimeError("❗ 가상계좌를 할당하지 못했습니다.")                       │
> │   261 │                                                                                          │
> │   262 │   def _get_tomorrow(self):                                                               │
> │   263 │   │   korea_tz = pytz.timezone("Asia/Seoul")                                             │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> RuntimeError: ❗ 가상계좌를 할당하지 못했습니다.

**Comment by roeniss** [comment]
https://github.com/roeniss/dhlottery-api/issues/107 와 동일한 root cause 를 가지고 있을 것 같습니다. 혹시 케이뱅크가 연동되어있지 않다던가... 하는 부분이 있으신가요? 🤔

**Comment by an14700** [comment]
음.. assign-virtual-account 기능이 가상계좌라고 생각했는데 아닌가요? 
충전하기 화면을 보면 '간편충전'과 '가상계좌 입금' 두가지가 있던데요. 
저는 가상계좌 입금을 의미한다고 생각했습니다. 

![스크린샷 2024-03-06 오전 7 19 42](https://github.com/roeniss/dhlottery-api/assets/11266203/2b63c3d2-aaec-476c-9007-01d052ec693b)
----------------------------------------------------------------
<img width="907" alt="스크린샷 2024-03-06 오전 7 24 31" src="https://github.com/roeniss/dhlottery-api/assets/11266203/9d61ace9-6c59-4b9f-9881-74c5b3f23636">

**Comment by roeniss** [comment]
> 음.. assign-virtual-account 기능이 가상계좌라고 생각했는데 아닌가요?
> 충전하기 화면을 보면 '간편충전'과 '가상계좌 입금' 두가지가 있던데요.
> 저는 가상계좌 입금을 의미한다고 생각했습니다

@an14700 이해하신게 정확합니다. 

일단 `assign-virtual-account` 의 작동방식을 말씀드리면, 위에 캡쳐해주신 두 번째 사진에서 "확인" 버튼을 누를 때 날아가는 request 와 동일한 request 를 서버로 전송합니다.

웹에서 "확인"을 누르면, 이후 예치금 충전 UI 로 리다이렉트 됩니다 (아래 사진 참고). 이 화면에서 `#contents span` 엘리먼트를 찾으면 그게 사진에서 하이라이트 된 부분입니다. 

![Screenshot 2024-03-07 at 02 19 52 by seonghyeok](https://github.com/roeniss/dhlottery-api/assets/26613280/d3d000cf-c448-42b8-b531-b7ea8770456e)

이 부분에 대한 캡쳐도 한 번 부탁드려도 될까요?

혹시 html selector 에 대해 알고 계시다면, `#contents span` 대신 어디에 계좌정보가 나오는지 체크해주시는 것도 도움이 될 것 같습니다.

계정을 새로 만들어서 해보려고 했는데, 중복 가입이 차단되어서... 제 쪽에서 확인하려면 시간이 조금 걸릴 것 같습니다 (~2 weeks)

**Comment by an14700** [comment]
<img width="931" alt="스크린샷 2024-03-07 오전 7 32 53" src="https://github.com/roeniss/dhlottery-api/assets/11266203/a79c310a-ac76-439f-80f9-2d5f969c0444">

`//*[@id="contents"]/table/tbody/tr[4]/td/span`

요청하신 캡쳐 이미지와 가상계좌의 xpath 정보입니다. 
그런데 roeniss님이 올려주신 이미지와 조금 다르네요. 제 화면에서는 '고정 가상계좌'가 아니라 '가상계좌'로 표시되고 있습니다. 
무언가 '간편 충전 계좌'의 유무에 따라 다르게 동작하는 걸까요? 

> 일단 assign-virtual-account 의 작동방식을 말씀드리면, 위에 캡쳐해주신 두 번째 사진에서 "확인" 버튼을 누를 때 날아가는 request 와 동일한 request 를 서버로 전송합니다.

여기서 설명해주신 '확인' 버튼을 누르면 제 경우에는 휴대폰 점유인증 팝업이 나옵니다. 휴대전화번호를 입력하면 인증문자가 발송되고, 인증번호를 입력하면 계좌번호가 나옵니다.

**Comment by roeniss** [comment]
> 요청하신 캡쳐 이미지와 가상계좌의 xpath 정보입니다.
> 그런데 roeniss님이 올려주신 이미지와 조금 다르네요. 제 화면에서는 '고정 가상계좌'가 아니라 '가상계좌'로 표시되고 있습니다.
> 무언가 '간편 충전 계좌'의 유무에 따라 다르게 동작하는 걸까요?

그런듯 하네요. 저는 제 케이뱅크 계좌를 동행복권 측에 연동해 둔 상태이고, 이게 영향을 주고 있는 것 같습니다.

- 저는 '가상계좌'가 케이뱅크 계좌입니다 (제가 연동한 계좌와는 다른, 새로운 계좌번호)
- 저는 '결제방식'이 "고정계좌 입금" 입니다.
- 저는 입금만료일시가 없습니다.

아무튼 이건 그냥 분기를 쳐서 대응하면 될 것 같은데 문제는, 

> 여기서 설명해주신 '확인' 버튼을 누르면 제 경우에는 휴대폰 점유인증 팝업이 나옵니다.  

이 경우는 좀 문제가 될 듯 합니다. `간편 충전` 탭 대신 `고정 가상계좌 입금` 탭을 선택한 것도, 팝업이 나오지 않고 (=유저 액션 필요하지 않고) 바로 진행할 수 있어서거든요.

그래서 이 부분은 아예 별도 이슈를 파서 진행하는게 좋겠습니다 ('케이뱅크 비연동 유저의 고정 가상계좌 입금 구현') . 이 이슈는 클로즈합니다만, 더 의견 나누고 싶으신 부분이 있다면 편하게 재오픈 부탁드립니다.
