### ISSUE TITLE
Google Colab, Codespace 에서 실행 시 구매 실패 

### ISSUE THREAD

**Issue by RIOARIGATO** [roeniss/dhlottery-api#113]
Google Colab, Codespace 에서 실행 시 구매에 실패합니다. 
자동, 수동, 반자동, 개수와 관계없이 모든 구매에서 실패가 발생합니다. 
이유를 알 수 있을까요?

```
KeyError: 'arrGameChoiceNum'

During handling of the above exception, another exception occurred:

RuntimeError: ❗ 로또6/45 구매에 실패했습니다.
```

**Comment by roeniss** [comment]
@no01pm 안녕하세요. 

1. `dhapi version` (최신버전) 또는 `dhapi -v` (구버전) 명령어로 버전을 알고 싶습니다. 
2. (credentials 정보를 제외하고) 해당 colab 을 공유받을 수 있을까요? 
3. `--debug` 옵션을 붙여서 출력이 달라지는지 확인해보시겠어요?

**Comment by roeniss** [comment]
아, 다행이네요. 수고하셨습니다!
