### ISSUE TITLE
매주 자동 구매하는 깃헙액션 만들기

### ISSUE THREAD

**Issue by roeniss** [roeniss/dhlottery-api#12]
reference : https://github.com/techinpark/lottery-bot/tree/main/.github/workflows

개인적으로, 저는 "최소한의 손맛"을 느끼기 위해, 매주 수동으로 스크립트를 실행해 구매하는 편에 만족하고 있습니다.

그러나 어떤 분은 위 레퍼런스처럼, 자동구매하는 Github Actions 를 하나 추가하는 쪽을 선호하실 것 같습니다.

만약 그런 분이 계시다면 주저없이 기여해주세요! 필요하시다면 서포트하겠습니다.

- [ ] 깃헙 액션 만들기
- [ ] https://github.com/marketplace?type=actions 마켓플레이스에 추가하기

**Comment by seongilp** [comment]
제가 테스트 해보고 있습니다. 완료되면 PR 올릴게요!

**Comment by roeniss** [comment]
오,, ㅎㅎ 잘부탁드립니다!

**Comment by seongilp** [comment]
#40 에 한번 만들어 봤습니다!

**Comment by roeniss** [comment]
@seongilp 제가 착각한 부분이 있어 여기에 코멘트를 추가 하겠습니다.

이 PR 의 목표는 제 레포에 github actions 가 추가되는 것이 아닙니다! 그러면 혜택을 보는 사람이 저이고, 다른 분들은 fork 를 떠야만 github action 이 유의미해질 것이기 때문에... 

상단 본문에 있듯이, market place 에 등록하는 것을 목표로 해야 합니다. 

예시: https://github.com/marketplace/actions/pypi-publish 

이런 식으로 마켓 플레이스에 등록하면, 다른 사람들은 따로 레포를 가지고 있지 않더라도, 혹은 pip install dhapi 하지 않더라도, 간단하게 깃헙 액션을 구동할 수 있을 것입니다. 

이 단계가 너무 복잡하다고 생각하시면 예전 (https://github.com/roeniss/dhlottery-api/pull/40) 처럼 PR 로 올려주세요. 그럼 머지 후 뒷작업 (마켓플레이스 등록)을 제가 이어 하겠습니다 ㅎㅎ 편하신 대로 부탁드려요!

**Comment by seongilp** [comment]
@roeniss 님, 매주 자동구매도 성공했고, marketplace에도 올렸습니다. 
처음 해보는 작업이라 손볼 곳이 많을 거 같은데요. 알려주시면 맞춰서 진행할게요!
https://github.com/marketplace/actions/buylotto645-weekly

**Comment by roeniss** [comment]
@seongilp 설명 가이드가 없어서 따라하는데 곤란한 상황입니다. 올려주신 링크 상에 가이드 문서가 있어야 할 것 같아요

**Comment by roeniss** [comment]
> 혹은 pip install dhapi 하지 않더라도, 간단하게 깃헙 액션을 구동할 수 있을 것입니다.

유저가 pip install 하지 않도록 만들수 있을까요? 즉, `uses` 한줄로 모든게 끝나야할 것 같아요 (환경변수는 예외적으로 OK 라 치고)

**Comment by seongilp** [comment]
@roeniss 네, 그렇게 해보겠습니다!

**Comment by roeniss** [comment]
https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action 공식 가이드를 참고해서 github action 만들어 배포예정

**Comment by roeniss** [comment]
@seongilp 곧 작업을 하게 될 것 같아서, 혹시 제가 맡아서 해도 될까요?

**Comment by seongilp** [comment]
@roeniss 네네 감사합니다!

**Comment by roeniss** [comment]
https://velog.io/@bang9dev/14줄의-코드로-로또-자동구매-설정하기 라는 포스팅에 의거하여 GitHub Actions 구현 계획을 폐기합니다
