### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by callor** [roeniss/dhlottery-api#2]
안녕하세요
좋은 소스코드 볼수 있어서 정말 좋습니다

최근 동행 로또 로그인 부분이 스크립트로 변경이 된 듯합니다
정상적인 로그인이 되지 않는 듯 하여 ISSUE 남겨 봅니다

감사합니다

**Comment by roeniss** [comment]
체크하겠습니다. 제보 감사드려요. @callor

**Comment by roeniss** [comment]
@callor 방금 리눅스 서버에서 dhapi 를 통해 이번주 동행복권을 구매 성공했습니다. 코드는 별도 수정이 필요 없다고 판단됩니다.

별도 이슈로 에러 로그를 올려주시면 같이 고민해볼 수 있을 것 같습니다. 본 이슈는 클로즈할게요!
