### ISSUE TITLE
default 파라미터 추가 의견

### ISSUE THREAD

**Issue by frogred8** [roeniss/dhlottery-api#4]
안녕하세요.
덕분에 커맨드 한 줄로 편하게 구입이 가능해서 좋네요. 기여 감사합니다.

그런데 대부분 고정인 파라미터들은 default값으로 넣는건 어떨까요?
대다수 사용자가 로또 구입이 목표일테니 현재 기준으로만 default를 설정해도 될 것 같아서요.
다만 어떤걸 사고 있는지 인지가 힘들 수 있으니 password 받기 전에 현재 구입하는 복권 타입들을 출력해줘도 좋고요.
그럼 아래처럼 id, 개수만으로 실행할 수 있을 것 같습니다.
dhapi -U $YOUR_ID -C 5

의견이니 참고만 해주세요. 다시 한번 감사합니다!

**Comment by roeniss** [comment]
그러면.. 말씀주신거에 얹어서,

기본 동작 자체를 (1) 커맨드 입력 (2) 어떤 복권 (6/45)을 어떤 방식(auto)으로 얼마나 (5) 살지 표시해주고 (3) y 를 입력하면 → 구매

단 --quiet (-q) 옵션을 붙이면 (3)을 생략하고 바로 구매 

하는 형태로의 변경은 어떻게 생각하세요?

**Comment by frogred8** [comment]
아하. 한번 확인하는 기능도 있으면 좋겠네요.
의견 받아주셔서 감사합니다!

**Comment by roeniss** [comment]
@frogred8 

```sh
pip3 install dhapi --upgrade  # 1.2.1
dhapi buy_lotto645 -u $USER_ID -q  # no confirm, buy 5 auto games
dhapi buy_lotto645 -u $USER_ID -p #USER_PW -q  # no confirm, buy 5 auto games, no additional password input
```
생각하신게 맞는지 테스트 한 번 부탁드립니다 :bow:

**Comment by frogred8** [comment]
오. 구매 확인도 가능해서 좋네요. 테스트덕분에 로또5장 더 산건 안비밀 ㅋㅋ  
간결해진 새 버전으로 크론탭에 등록해두고 잘 사용하겠습니다. 감사합니다!
