### ISSUE TITLE
[docs] crontab example

### ISSUE THREAD

**Issue by seunggabi** [roeniss/dhlottery-api#42]
I suggest to add `crontab -e example code` on `README.md`.

```
crontab -e 

0 0,6-23 * * * PATH=$PATH:/opt/homebrew/bin && dhapi buy_lotto645 -q
```

**Comment by roeniss** [comment]
Sadly, closed by this comment: https://github.com/roeniss/dhlottery-api/pull/43#issuecomment-1584858381
