### ISSUE TITLE
[credentials] multiple

### ISSUE THREAD

**Issue by seunggabi** [roeniss/dhlottery-api#44]
I suggest to use multiple account. (like aws credentials.)

### `# cat ~/.dhapi/credentials`
```
[default]
id = asdf
pw = 1234

[sg]
id = qwer
pw = 5678

...
```

### cmd
```
dhapi buy_lotto645 -q # default
dhapi buy_lotto645 -q --profile sg # sg
```

I will make pr. thx

**Comment by roeniss** [comment]
@seunggabi not important thing but you'd better remove the pr number in each commit message. As you can see above, your commits are distracting the issue page.

**Comment by seunggabi** [comment]
> @seunggabi not important thing but you'd better remove the pr number in each commit message. As you can see above, your commits are distracting the issue page.

hmm.. I don't agree with you.
commit & pr connection is important.

I use this. https://myeongjae.kim/blog/2019/02/02/prepare-commit-msg-hook-issue-number

**Comment by roeniss** [comment]
You are connecting each commit to this Issue. 
But in reality, the only matter is the code in the Pull Request. So the relation should be like this:

```
Issue A ㅡ Pull Request B ㅡ Branch C ㅡ Commit D (HEAD)
                                                                           |
                                                                    Commit E
                                                                           |
                                                                    Commit F
```

When you mention the issue number in each commit message, you are actually breaking this relation and just connecting each commit to the issue right away. What does that mean? Does it have something to you? What would happen if you don't connect it? Is there any problem?

**Comment by seunggabi** [comment]
늦게 봣네요.. merge 감사합니다.ㅎㅎ!
