### ISSUE TITLE
에러: "비정상적인 방법으로 접속하였습니다. 정상적인 PC 환경에서 접속하여 주시기 바랍니다."

### ISSUE THREAD

**Issue by HyunsooCha** [roeniss/dhlottery-api#47]
[Lotto645 Buy Request]
Game A: []
Game B: []
Game C: []
Game D: []
Game E: []

❓ 위와 같이 구매하시겠습니까? [Y/n] yes
✅ --quiet 플래그가 주어져 자동으로 구매를 진행합니다.
2023-06-25 08:14:33 [error    ] 🚨 에러가 발생했습니다: 구매에 실패했습니다: 비정상적인 방법으로 접속하였습니다. 정상적인 PC 환경에서 접속하여 주시기 바랍니다.
🚨 에러가 발생했습니다: 구매에 실패했습니다: 비정상적인 방법으로 접속하였습니다. 정상적인 PC 환경에서 접속하여 주시기 바랍니다.

이러한 메시지가 나오면서 안됩니다 ㅠㅠ 맥이나 우분투 둘다 시도했는데 동일합니다. 1.4.0버전이고 1.3.5 버전에서도 유사한 에러가 나옵니다. 저번주까지는 되었는데 이번주에는 갑자기 안되네요 ㅠㅠ 어떻게 해결하면 될까요?

**Comment by roeniss** [comment]
아 이건 좀 심각하네요.. 새 패치가 나올때까진 어쩔 수 없이 dhapi 잠시 놓아주시길 바랍니다 ㅠ.ㅠ

**Comment by seunggabi** [comment]
이건 너무 한거 아니냐고 ㅠ..ㅜ

**Comment by seunggabi** [comment]
https://ol.dhlottery.co.kr/olotto/game/egovUserReadySocket.json
INTCOM1, INTCOM2 socket 으로 뭔가 되나보네요.

**Comment by songmw90** [comment]
타 repo에 PR한 내용이지만 참고하세요
https://github.com/techinpark/lottery-bot/pull/2

**Comment by roeniss** [comment]
이 이슈 해결되었습니다. 곧 신 버전 배포하겠습니다

**Comment by roeniss** [comment]
https://github.com/roeniss/dhlottery-api/releases/tag/v2.0.0 이 링크에서 마이그레이션 방법 제공하였습니다!
