### ISSUE TITLE
연금복권 (win720) 구현

### ISSUE THREAD

**Issue by songmw90** [roeniss/dhlottery-api#5]
https://github.com/techinpark/lottery-bot/blob/main/win720.py

이 api를 이용한 자동화 repo를 먼저 알게 되어 win720 구현 후 PR 했는데요, 만약 여기에 PR할 생각있으신분은 참고하시라고 이슈에 남깁니다.. 

저는 제가 쓸거라 무조건 5장을 구매하도록 했기때문에, 이 API에서는 옵션으로 장 수를 선택하는 작업이 필요합니다

**Comment by roeniss** [comment]
레퍼런스에 제 레포를 적어주시다니 영광입니다... GA를 이용한 자동화가 인상적이군요. 저는 손맛(??)을 느끼기 위해 매주 직접 구매하고 있긴 합니다만 자동화도 정말 매력적인 포인트로 보입니다.

**Comment by roeniss** [comment]
당장 구현 계획이 없어서 클로즈합니다
