### ISSUE TITLE
로또 회차 확인 실패로 구매 불가

### ISSUE THREAD

**Issue by roeniss** [roeniss/dhlottery-api#52]
html 이 바뀐 것으로 추정됨.

**Comment by roeniss** [comment]
resolved by https://github.com/roeniss/dhlottery-api/pull/53, https://github.com/roeniss/dhlottery-api/pull/54

**Comment by seunggabi** [comment]
@roeniss 이거 배포되었나요!? ㅜ
에러나는것 같습니다?

**Comment by roeniss** [comment]
또 바뀐건가 싶네요 ㅠ 2.0.5 배포하겠습니다
