### ISSUE TITLE
user 옵션 관련 문의

### ISSUE THREAD

**Issue by qkdrk777777** [roeniss/dhlottery-api#59]
혹시 -u 옵션에서 passwd 묻지 않고 옵션으로 받을 수 있는 기능이 있나요?

없으면 구현하실 예정이 있으신가요?

**Comment by roeniss** [comment]
현재 최신 버전에서는 비밀번호를 콘솔에 입력하는 것을 지양하고 있습니다.
자세한 내용은 리드미의 [계정 정보 세팅](https://github.com/roeniss/dhlottery-api#%EA%B3%84%EC%A0%95-%EC%A0%95%EB%B3%B4-%EC%84%B8%ED%8C%85) 섹션을 참고해주세요 :D @qkdrk777777
