### ISSUE TITLE
완전 자동화를 위해서 비밀번호 파라메터화 + 잔액 노출이 가능할까요? 

### ISSUE THREAD

**Issue by hansu35** [roeniss/dhlottery-api#6]
자동화를 하고 싶은데 문제는 비밀번호를 입력하는 부분이 있어서 자동화가 어려울듯해서 비밀번호를 넣어주는 부분을 파라매터로 수정가능하실까요? 

또한 잔액이 확인 가능하면 일정수준 이하의 잔액이 남았을때 알려줄수 있을듯해서 
남은 잔액 정보가 있다면 출력이 가능하실까요?

**Comment by roeniss** [comment]
둘 다 가능할 것 같습니다만 언제 완료가 된다고 말씀드리긴 어려울 것 같습니다. 의견 감사해요. 완료되면 여기서 멘션 드리겠습니다.

**Comment by hansu35** [comment]
감사합니다.

**Comment by roeniss** [comment]
@hansu35 

> 자동화를 하고 싶은데 문제는 비밀번호를 입력하는 부분이 있어서 자동화가 어려울듯해서 비밀번호를 넣어주는 부분을 파라매터로 수정가능하실까요?

에 대하여,

```sh
pip3 install dhapi --upgrade  # 1.2.1
dhapi buy_lotto645 -u $USER_ID -p $USER_PW -q  # no password ask, no check-before-buy, just buy 5 auto games
```

를 한 번 테스트 부탁드립니다 @hansu35

**Comment by hansu35** [comment]
Fail to purchase (reason: [온라인복권 주간 구매한도] 초과되었습니다.)

테스트 한다고 몇장을 샀더니 더이상 구매가 안되네요. 
로그인과 구매까지 잘 진행되는것 같습니다. 

빠르게 추가 해 주셔서 감사합니다. 

다만 혹시 기존에 옵션으로 있었던 갯수는 여전히 받게 추가 수정가능 하실까요? 
저는 매주 한장씩 구매하려고 하거든요..

**Comment by roeniss** [comment]
```sh
dhapi -h
dhapi buy_lotto645 -u $USER_ID -p $UWER_PW -q -g "*,*,*,*,*,*" # 한 장 자동으로 구매
```
이렇게 하시면 됩니다! 다음주에 한번 체크 부탁드립니다 이번주는 저도 다 사서..

**Comment by hansu35** [comment]
![image](https://user-images.githubusercontent.com/6380779/229025563-d8ab0323-717c-47f5-9d1a-cbceb4e2d41b.png)

한장 구매성공했습니다. 

감사합니다.
