### ISSUE TITLE
buy_lotto645를 제외한 향후 API 기능 추가 계획 문의

### ISSUE THREAD

**Issue by Mikeds36** [roeniss/dhlottery-api#61]
현재 API가 아래와 같이 작동하고 있는데, 이는 향후 기능 추가를 위해 남겨진 것인지, 아니면 아래와 같이 수정해도 되는지 궁금합니다.

현재
❯❯❯ dhapi buy_lotto645 -q

제안
❯❯❯ dhapi -q

'buy_lotto645'를 넘어서 다른 기능들을 추가할 계획이 있는지, 혹은 제안한 API의 변경사항이 향후 계획과 부합하는지 확인해주실 수 있나요?

**Comment by roeniss** [comment]
> 향후 기능 추가를 위해 남겨진 것인지
> 'buy_lotto645'를 넘어서 다른 기능들을 추가할 계획이 있는지

맞습니다. 그러나 딱히 기능추가 계획은 일정에 없습니다.

제안해주신건 향후 계획과 상충하나, 그렇게까지 중요한 것은 아닙니다. 다만 말씀주신 제안 코드는 

```
alias dhapi="dhapi buy_lotto645" 로 충분한 것 같아서, 확장성 (일정엔 없지만) 을 굳이 막는 쪽으로의 디자인이 유의미할까 하는 생각이 듭니다.

**Comment by Mikeds36** [comment]
아하. 그렇군요..
답변 감사드립니다
