### ISSUE TITLE
계정 정보 입력을 위한 커맨드 라인 기능 추가 요청

### ISSUE THREAD

**Issue by Mikeds36** [roeniss/dhlottery-api#62]
현재 사용자는 dhapi에 다음과 같이 사용자 정보를 입력합니다:
```
DHAPI_USERNAME=qwer
DHAPI_PASSWORD=5678

cd ~/.dhapi

echo "" >> credentials
echo "[qwer]" >> credentials
echo username = $DHAPI_USERNAME >> credentials
echo password = $DHAPI_PASSWORD >> credentials
```

이 방법은 일반 사용자에게 어려울 수 있고, 새로운 사용자에게 README.md 파일을 읽어야 한다는 불편함이 있습니다.
따라서, 아래와 같은 기능 추가를 제안합니다.

---

제안 1:
```
>>> dhapi buy_lotto645
계정 정보가 존재하지 않습니다. 계정 정보를 입력해주세요.
Username:
Password:
```
이 경우, Username을 입력하면 해당 사용자에 맞는 계정 정보가 생성되며, 파일에는 아래와 같이 저장되면 좋을 것 같습니다.
```
[default]
Username: (사용자 ID)
Password: (사용자 PW)
```

---

제안 2:
```
>>> dhapi buy_lotto645 -p asdf
프로필 명에 해당하는 계정 정보가 존재하지 않습니다. 계정 정보를 입력해주세요.
(위와 동일)
```
이 경우, 커맨드 라인에서 프로파일 명을 입력하였으므로, Username을 입력하였을 때 계정 정보가 생성되며, 파일에는 아래와 같이 저장되면 좋을 것 같습니다.
```
[asdf]
Username: (사용자 ID)
Password: (사용자 PW)
```

**Comment by roeniss** [comment]
꽤 괜찮은 것 같은데... 혹시 작업해보실 의향이 있으신가요? (간절한 눈빛)

**Comment by Mikeds36** [comment]
시간이 된다면 한번 해보겠습니다 ㅎㅎ

**Comment by roeniss** [comment]
작업하시기 편하게 약간 코드를 [수정](https://github.com/roeniss/dhlottery-api/blob/main/src/dhapi/router/credentials_provider.py)해두었습니다. 티가 안날 수도 있습니다만...  모쪼록 잘부탁드립니다! :D

**Comment by roeniss** [comment]
@Mikeds36 안녕하세요, 지금까지 #63 이 @Mikeds36 님의 작업이라고 생각했는데 서로 다른 분이셨군요... 이 작업은 rlatn1234 님이 하시게 되었습니다. 미리 양해를 구했어야 되었는데 죄송합니다.
