### ISSUE TITLE
사용자 계정 정보 세팅 관련 문서내용 개선

### ISSUE THREAD

**Issue by SeungHo0422** [roeniss/dhlottery-api#64]
현재 `readme.md`에는 사용자 계정 정보 입력 관련하여 다음과 같이 기재되어 있습니다.
---
`~/.dhapi/credentials` 파일에 username, password를 입력하면 자동으로 로그인합니다.
profile을 여러개 설정할 수 있습니다.

> [!NOTE]
> TOML 문법을 사용합니다. 따라서 value 값은 쌍따옴표를 사용해야 합니다.

```sh
DHAPI_USERNAME=asdf
DHAPI_PASSWORD=****

mkdir -p ~/.dhapi
cd ~/.dhapi

echo "[default]" > credentials
echo username = "$DHAPI_USERNAME" >> credentials # username
echo password = "$DHAPI_PASSWORD" >> credentials # password (미리 복잡한 난수로 변경하시길 권장합니다)
```
---
<br>
문서에 기재된 스니펫 예시만 보고 입력했을 때, value 값에 쌍따옴표가 붙지 않기 때문에 tomli.TOMLDecodeError가 발생함을 확인할 수 있습니다.
비록 NOTE를 통해 value 값은 쌍따옴표를 사용해야 함을 알렸지만, 실제 사용자는 스니펫에 더욱 의존하며 진행할 가능성이 크기 때문에 다음과 같이 제안드립니다.

### 제안1 : 문서 개선
```sh
DHAPI_USERNAME=\"asdf\"
DHAPI_PASSWORD=\"****\"

mkdir -p ~/.dhapi
cd ~/.dhapi

echo "[default]" > credentials
echo username = "$DHAPI_USERNAME" >> credentials # username
echo password = "$DHAPI_PASSWORD" >> credentials # password (미리 복잡한 난수로 변경하시길 권장합니다)
```
위와 같이 \를 명시해줌으로써 쌍따옴표가 static하게 입력됨을 알려주면 좋을 듯 합니다.

### 제안2 : 리팩토링
credentials 파일에는 쌍따옴표 없이 들어오므로, `arg_parser.py`에서 이를 toml의 value값으로 인식되게끔 코드를 개선할 수 있습니다.

**Comment by roeniss** [comment]
문서 개선이 좀 더 빠를 것 같네요. 혹시 기여해주실 의향이 있으신지요?

**Comment by SeungHo0422** [comment]
물론이죠!
